version: "3.9"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bitburner
      POSTGRES_DB: bitburner
      POSTGRES_PASSWORD: bitburner
